npmRegistryServer: "https://registry.npmjs.org/"
npmAuthToken: ${NODE_AUTH_TOKEN-}

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: node-modules

# TODO: This breaks the current eslint/prettier shared configuration. Revert back to using
# `node-modules` linker until we find a better solution.
#
# nodeLinker: pnpm
#
# # NOTE: The following section is necessary to support `nodeLinker: pnpm` because the following
# # libraries include phantom dependencies and are required by `@metamask/snaps-cli` which is
# # required by arsnap.
# packageExtensions:
#   ethjs-query@*:
#     dependencies:
#       babel-runtime: "6.26.0"
#   ethjs-contract@*:
#     dependencies:
#       babel-runtime: "6.26.0"
#       promise-to-callback: "1.0.0"
#   eth-block-tracker@4.4.3:
#     dependencies:
#       "@babel/core": "7.5.5"
#   "@pianity/arsnap@*":
#     dependencies:
#       "@babel/runtime": "7.5.5"
#
#   "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
#     dependencies:
#       typescript: ">=2.7"
