nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

# NOTE: The following section is necessary to support `nodeLinker: pnpm` because the following
# libraries include phantom dependencies and are required by `@metamask/snaps-cli` which is
# required by arsnap.
packageExtensions:
  ethjs-query@*:
    dependencies:
      babel-runtime: "6.26.0"
  ethjs-contract@*:
    dependencies:
      babel-runtime: "6.26.0"
      promise-to-callback: "1.0.0"
  eth-block-tracker@4.4.3:
    dependencies:
      "@babel/core": "7.5.5"
  "@pianity/arsnap@*":
    dependencies:
      "@babel/runtime": "7.5.5"
