name: "Publish Package to NPM Registry"

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      # Setup .npmrc file to publish to npm
      - uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@pianity"

      - name: "Install dependencies"
        run: "yarn install"

      - name: "Build packages"
        run: "yarn build"

      - name: "Deploy packages to NPM"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: "yarn workspace @pianity/arsnap npm publish --access public"
